--ALTER SESSION SET CONTAINER = cdb$root;
clear screen
/
ALTER SESSION SET HEAT_MAP = 'ON'
/
SHOW CON_NAME
/
ALTER SESSION SET CONTAINER = pdb1;
/
SHOW PARAMETER heat_map;
/
--create table t2 (c varchar(256)) tablespace users
/
--insert into t2 values('hola')
/
insert into t2 select * from t2
/
commit
/
select * from t2 where rownum < 3
/
COLUMN object_name FORMAT A20
/
SELECT track_time,
       object_name,
       n_segment_write,
       n_full_scan,
       n_lookup_scan
FROM   v$heat_map_segment
ORDER BY 1, 2;
/
SELECT SUBSTR(OBJECT_NAME,1,20), SUBSTR(SUBOBJECT_NAME,1,20), TRACK_TIME, SEGMENT_WRITE,
  FULL_SCAN, LOOKUP_SCAN FROM V$HEAT_MAP_SEGMENT;
/
SELECT SUBSTR(OBJECT_NAME,1,20), SUBSTR(SUBOBJECT_NAME,1,20), SEGMENT_WRITE_TIME,
  SEGMENT_READ_TIME, FULL_SCAN, LOOKUP_SCAN FROM USER_HEAT_MAP_SEGMENT;
/
SELECT SUBSTR(OBJECT_NAME,1,20), SUBSTR(SUBOBJECT_NAME,1,20), TRACK_TIME, SEGMENT_WRITE, FULL_SCAN,
  LOOKUP_SCAN FROM USER_HEAT_MAP_SEG_HISTOGRAM;
/
SELECT SUBSTR(OWNER,1,20), SUBSTR(OBJECT_NAME,1,20), OBJECT_TYPE, SUBSTR(TABLESPACE_NAME,1,20),
    SEGMENT_COUNT FROM DBA_HEATMAP_TOP_OBJECTS ORDER BY SEGMENT_COUNT DESC;
/
SELECT SUBSTR(TABLESPACE_NAME,1,20), SEGMENT_COUNT 
    FROM DBA_HEATMAP_TOP_TABLESPACES ORDER BY SEGMENT_COUNT DESC;
/
SELECT COUNT(*) FROM DBA_HEATMAP_TOP_OBJECTS;
/
SELECT COUNT(*) FROM DBA_HEATMAP_TOP_TABLESPACES;
/